// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Try env vars first, fall back to hardcoded cloud project
const rawUrl = (import.meta.env.VITE_SUPABASE_URL || "").trim();
const rawKey = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "").trim();

// Supabase Cloud project credentials (anon key is public)
const CLOUD_URL = "https://svvbfshcpetazsrgnyac.supabase.co";
const CLOUD_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2dmJmc2hjcGV0YXpzcmdueWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4NzMxNDMsImV4cCI6MjA5NDQ0OTE0M30.7cgDQjvVClYYpqaIiU7acrM2_sGKFsqmKndvcw4cyHI";

let FINAL_URL = rawUrl;
let FINAL_KEY = rawKey;

if (!rawUrl) {
  console.log("[Supabase] Usando credenciais cloud (nenhuma VITE_SUPABASE_URL configurada)");
  FINAL_URL = CLOUD_URL;
}
if (!rawKey) {
  FINAL_KEY = CLOUD_KEY;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(FINAL_URL, FINAL_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? sessionStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
  },
});