// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const rawUrl = (import.meta.env.VITE_SUPABASE_URL || "").trim();
const rawKey = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "").trim();

console.log("[Supabase] VITE_SUPABASE_URL:", rawUrl ? rawUrl.substring(0, 30) + "..." : "(vazio)");
console.log("[Supabase] VITE_SUPABASE_PUBLISHABLE_KEY:", rawKey ? rawKey.substring(0, 20) + "..." : "(vazio)");

if (!rawUrl) {
  console.warn("[Supabase] VITE_SUPABASE_URL não definida no Vercel.");
}
if (!rawKey) {
  console.warn("[Supabase] VITE_SUPABASE_PUBLISHABLE_KEY não definida no Vercel.");
}

// Validate URL
let SUPABASE_URL = rawUrl.trim();
try {
  if (SUPABASE_URL) new URL(SUPABASE_URL);
} catch {
  console.warn(`[Supabase] URL inválida: "${SUPABASE_URL}". Usando fallback local.`);
  SUPABASE_URL = "";
}

const FINAL_URL = SUPABASE_URL || "http://127.0.0.1:54321";
const FINAL_KEY = rawKey.trim() || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(FINAL_URL, FINAL_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});